kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-registry-creds
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  .dockerconfigjson: >-
    {{ .Values.secrets.registryEncodedDockerConfigJson }}
type: kubernetes.io/dockerconfigjson
