---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-springboot-app-prod
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-na-ssa/my-springboot-app-gitops
    targetRevision: HEAD
    path: ./helm/app
    helm:
      parameters:
      - name: namespace.name
        value: my-springboot-app-prod
      - name: environment
        value: prod
      - name: image.tag
        value: prod
  destination:
    server: https://api.cluster-ggp92.ggp92.sandbox1233.opentlc.com:6443
    namespace: my-springboot-app-prod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
