---
apiVersion: v1
kind: Secret
metadata:
  name: my-springboot-app-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/redhat-na-ssa/my-springboot-app-gitops